name: Expo CI/CD

on:
  push:
    branches:
      - master # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Setup Yarn & Expo cli
        run: npm i -g yarn eas-cli

      - name: Install dependencies
        run: yarn install

      - name: Test Code
        run: yarn test

      - name: Build Expo project
        run: expo build:android # Replace with the build command for your platform (e.g., expo build:android, expo build:ios, etc.)

      - name: Clean up
        run: expo clean